[Feat] Login Screen
9oormthonUNIV-3th-KGU/family-note-ui pull request #3
Opened 2024-09-11 14:21 UTC by boroboro01

## #️⃣연관된 이슈

#2 

## 📝작업 내용

<img width="1887" alt="image" src="https://github.com/user-attachments/assets/f35a413a-48f3-4eb7-9f87-7dd09d3e5c61">

### 스크린샷 (선택)

## 💬리뷰 요구사항(선택)

```
const Button = styled.button<{ isPrimary: boolean }>`
  background-color: ${(props) => (props.isPrimary ? '#ffa800' : '#ffffff')};
  color: ${(props) => (props.isPrimary ? '#ffffff' : '#000000')};
  font-family: Inter;
  font-style: normal;
  font-size: ${(props) => (props.isPrimary ? '30px' : '26px')};
  font-weight: ${(props) => (props.isPrimary ? '700' : '500')};
  border: none;
  border-radius: 5px;
  padding: 5px 10px;
  margin-bottom: 15px;
  cursor: pointer;
  width: 100%;
`

const Image = styled.img<{
  top?: string
  bottom?: string
  left?: string
  right?: string
}>`
  position: absolute;
  top: ${({ top }) => top || 'auto'};
  bottom: ${({ bottom }) => bottom || 'auto'};
  left: ${({ left }) => left || 'auto'};
  right: ${({ right }) => right || 'auto'};
`
```
이미지와 버튼은 props를 통해서 하나의 스타일을 재활용 했습니다!

2024-09-11 16:06 UTC, gmlwlsdl requested changes
이미지랑 버튼을 재활용한 점이 코드의 효율성 측면에서 좋은 거 같아요 ✨

2024-09-11 16:06 UTC, gmlwlsdl commented on src/pages/Auth.tsx
> +  }
닉네임 인풋 창 보더 트랜지션은 안 주셔도 되고, 동일한 색상 값으로 커서 색상에 변화만 주시면 될 거 같아요!
피그마 코멘트에 해당 부분 얘기가 있어서 확인해 보시면 좋을 거 같습니당

2024-09-11 16:06 UTC, gmlwlsdl commented on src/pages/Auth.tsx
> +        ></Image>
로고와 도형을 png 대신 svg로 저장하신 이유를 알 수 있을까요?

2024-09-11 16:06 UTC, gmlwlsdl commented on src/pages/Auth.tsx
> +  }
위 코드상으로는 인풋 창 크기가 `432*48`인데 디자인은 `417*54`라서 맞춰주시면 좋을 거 같아요!

2024-09-11 16:06 UTC, gmlwlsdl commented on src/pages/Auth.tsx
> +              <FormLabel>비밀번호</FormLabel>
닉네임 인풋 창과 비밀번호 라벨 사이 간격 `35px`로 맞춰주시면 감사하겠습니당

2024-09-11 16:06 UTC, gmlwlsdl commented on src/pages/Auth.tsx
> +            <Button isPrimary={isPrimary}>로그인</Button>
비밀번호 인풋 창과 로그인 버튼 사이 간격 `66px`로 맞춰주시면 감사하겠습니당

2024-09-11 16:06 UTC, gmlwlsdl commented on src/pages/Auth.tsx
> +            <Button isPrimary={!isPrimary}>회원가입</Button>
로그인 버튼과 회원가입 버튼 사이 간격 `20px`로 맞춰주시면 감사하겠습니당

2024-09-11 16:06 UTC, gmlwlsdl commented on src/pages/Auth.tsx
> +        ></Image>
파란 도형의 경우에는 우측 하단 모서리에서 좌측으로 조금 떨어져 있어서 이 부분 적용해 주시면 좋을 거 같아요

2024-09-12 05:12 UTC, boroboro01 commented on src/pages/Auth.tsx
> +  }
코멘트를 몰랐네요! 해당 부분 확인하고 수정하겠습니다!

2024-09-12 05:13 UTC, boroboro01 commented on src/pages/Auth.tsx
> +        ></Image>
SVG가 벡터 형태라서 파일 크기, SEO 최적화 등 여러 advantage가 있는 것으로 알고 있습니다!

2024-09-12 05:49 UTC, boroboro01 commented on src/pages/Auth.tsx
> +        ></Image>
요구사항 모두 수정 완료되었습니다!

2024-09-12 13:34 UTC, gmlwlsdl requested changes
수정해주신 부분 모두 확인했습니다!

추가로 상태 관리 부분 다시 요청드려요, 그리고 반복되는 `<Image>`, 닉네임 인풋 폼, 비밀번호 인풋 폼, 로그인 버튼, 회원가입 버튼 등은 컴포넌트로 만들 수 있어요!
해당 컴포넌트들을 조합해서 auth 페이지를 더욱 간결하게 작성할 수 있고, 편리하게 유지보수할 수 있는 장점이 있습니당

한번에 말씀드렸어야 했는데 번거롭게 해드려서 죄송합니다 ㅠㅠ

2024-09-12 13:34 UTC, gmlwlsdl commented on src/pages/Auth.tsx
> +  const [isPrimary, setIsPrimary] = useState(true)
useState 말고 zustand로 상태 관리 해주시면 좋을 거 같습니다!

2024-09-12 13:36 UTC, gmlwlsdl commented on src/pages/Auth.tsx
> +        ></Image>
아하 넵 알겠습니다 감사합니다!

2024-09-13 02:43 UTC, boroboro01 commented on src/pages/Auth.tsx
> +  const [isPrimary, setIsPrimary] = useState(true)
컴포넌트 분리를 처음 부터 했어야 했는데 제가 너무 막 해버렸네요

배경 이미지, 폼, 버튼 세 컴포넌트 분리되었습니다!

그리고 저 상태관리 부분은 사용하지 않는 코드인데 남아있었네요! 삭제했습니다

2024-09-13 05:31 UTC, gmlwlsdl approved these changes
모두 확인했습니다 머지하겠습니다!

2024-09-13 05:32 UTC, merged