[FEAT] create search screen with popup
9oormthonUNIV-3th-KGU/family-note-ui pull request #7
Opened 2024-09-16 08:17 UTC by boroboro01

## #️⃣연관된 이슈

> #6 

## 📝작업 내용

- Search screen UI
- Search box component
- Search bar component
- Popup component

### 스크린샷 (선택)

![splash-1](https://github.com/user-attachments/assets/d3334c3d-d007-444e-a048-d81ec0405692)

## 💬리뷰 요구사항(선택)

> 팝업창이 화면 크기에 안맞아서 우선 새로 만들어 보았습니다...!

2024-09-16 08:54 UTC, gmlwlsdl requested changes
초대 화면은 아래와 같이 앞으로 조금 나와있는(?) 형태로 되어 있어요!
<img width="364" alt="image" src="https://github.com/user-attachments/assets/a4566b75-041c-4a75-bfa4-055e929bd12c">

초대에 선택된 사용자를 확인하고 싶으면 초대 창 외부를 클릭하면 올려주신 pr에 있는 SearchBox 컴포넌트에 아이콘만 바꿔 랜딩되게 하면 될 것 같습니다!

추가로, 코멘트 부분도 확인해 주시면 감사하겠습니다!

2024-09-16 08:54 UTC, gmlwlsdl commented on src/components/Popup.tsx
> +  border-radius: 10px;
팝업 보더 37px로 맞춰주시면 감사하겠습니다!

2024-09-16 09:16 UTC, boroboro01 commented on src/components/Popup.tsx
> +  border-radius: 10px;
팝업 보더 수정하겠습니다!

2024-09-16 09:19 UTC, boroboro01 commented on src/components/Popup.tsx
> +  border-radius: 10px;
저는 디자인이 왜 두 개인가 했는데
팝업 형태로 컴포넌트가 올라와 있는 거 였네요
검색창 나오도록 수정하겠습니다

2024-09-16 10:47 UTC, boroboro01 commented
> 초대 화면은 아래와 같이 앞으로 조금 나와있는(?) 형태로 되어 있어요! <img alt="image" width="364" src="https://private-user-images.githubusercontent.com/108905670/367694843-a4566b75-041c-4a75-bfa4-055e929bd12c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0Nzg0MzMsIm5iZiI6MTcyNjQ3ODEzMywicGF0aCI6Ii8xMDg5MDU2NzAvMzY3Njk0ODQzLWE0NTY2Yjc1LTA0MWMtNGE3NS1iZmE0LTA1NWU5MjliZDEyYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxNlQwOTE1MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MGVmZmE1ZTZjNDM0NmFhOGU0MDc1NzQzNjBmZmUwZTA2ZTFkYzY3YzA5YWY3Y2RmNDRmM2M2NmFiMGE3ZDY4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ag5ebKtR6elG1X-LfOQsgoSKHZNkppUFB2GZ4td4IDs">
> 
> 초대에 선택된 사용자를 확인하고 싶으면 초대 창 외부를 클릭하면 올려주신 pr에 있는 SearchBox 컴포넌트에 아이콘만 바꿔 랜딩되게 하면 될 것 같습니다!
> 
> 추가로, 코멘트 부분도 확인해 주시면 감사하겠습니다!

검색 박스 구현 완료했습니다!

그리고 박스 띄우기 관련해서
클릭 메서드를 단순하게 넣는 방식으로는 한계가 있네요...!
아래 영상 참고해서 리액트 훅을 통해서 외부 클릭(박스와 검색바가 아닌 부분)시 사라지는 검색 박스를 구현했습니다
https://www.youtube.com/watch?v=HfZ7pdhS43s

+완료 팝업에도 같은 기능과 애니메이션이 추가되었습니다!

2024-09-16 12:02 UTC, gmlwlsdl requested changes
팝업 외부 클릭시 잘 닫히네요! 적절한 애니메이션도 들어가서 보기에 더 좋은 거 같습니당
코멘트 확인 한 번만 더 해주시면 감사하겠습니다 🙇‍♀️

2024-09-16 12:02 UTC, gmlwlsdl commented on src/components/Popup.tsx
> +  font-family: Pretendard;
피그마에서 `Pretendard` 폰트인 부분은 모두 `Pretendard Variable`로 해주셔야 정상적으로 반영됩니다!

2024-09-16 12:02 UTC, gmlwlsdl commented on src/components/Popup.tsx
> +  font-style: semibold;
semibold는 font-weight로만 받아서 요 부분들은 다 지워주셔도 될 거 같습니다!

2024-09-16 12:02 UTC, gmlwlsdl commented on src/components/Popup.tsx
> +  font-weight: 700;
semibold의 font-weight는 600입니당

2024-09-16 12:02 UTC, gmlwlsdl commented on src/components/ListItem.tsx
> +const Icon = styled(TiMinus)`
가족 구성원을 추가하는 컴포넌트에선 `TiPlus` 아이콘, 가족 구성원을 확인하고 삭제할 수 있는 컴포넌트에선 `TiMinus` 아이콘 써주시면 될 거 같습니다!

2024-09-16 12:02 UTC, gmlwlsdl commented on src/components/TextButton.tsx
>    width: 417px;
TextButton의 Button 보더도 `9px`로 변경해 주시면 감사하겠습니다!

2024-09-16 13:34 UTC, boroboro01 commented on src/components/TextButton.tsx
>    width: 417px;
언급된 부분 모두 수정되었습니다!

2024-09-16 14:21 UTC, gmlwlsdl requested changes
넵 모두 확인했습니다! 이번 코멘트가 마지막 요청일 거 같습니다 🙇‍♀️

2024-09-16 14:21 UTC, gmlwlsdl commented on src/components/Popup.tsx
> +  font-family: Pretendard;
요기도 변경해주셔야 해요!
```suggestion
  font-family: Pretendard Variable;
```

2024-09-16 14:21 UTC, gmlwlsdl commented on src/components/ListItem.tsx
> +const Text = styled.p`
```suggestion
const Text = styled.p`
  position: relative;
  top: 6px;
```

위 코드를 추가로 적용하면 텍스트 상하가 더욱 정렬되어 보여요!
<img width="431" alt="image" src="https://github.com/user-attachments/assets/c6152841-7a18-4752-a6d8-f0eb393e1663">

2024-09-16 17:55 UTC, boroboro01 commented on src/components/ListItem.tsx
> +const Text = styled.p`
전체 수정 완료되었습니다!

2024-09-17 01:09 UTC, gmlwlsdl approved these changes
모두 확인했습니다, 수고하셨습니다 👍

2024-09-17 01:09 UTC, merged